name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # HTML 파일을 푸시할 브랜치

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Repository 복제
      - name: Check out the repository
        uses: actions/checkout@v3

      # node.js 환경 설정
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm

      - name: Build the project
        run: npm run build 

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: .
